# Generated by Django 6.0.4 on 2026-05-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_task_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='points',
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baixa', 'Baixa')], default='media', max_length=10),
        ),
    ]
